services:
  postgres:
    image: postgres:latest
    container_name: chatLLM-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    restart: always

volumes:
  pgdata:
